add_newline = false

[sudo]

[battery]
disabled = true

[character]
format = "$symbol "

[crystal]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = "…/"
read_only = " "

[cmd_duration]
min_time = "10s"
format = "took [$duration](white)"

[git_branch]
symbol = " "
truncation_length = 6
truncation_symbol = "…"

[git_status]
# ahead = "🏎💨"
# behind = "😰"
# conflicted = "🏳"
# deleted = "🗑"
# diverged = "😵"
# modified = "📝"
# renamed = "👅"
# stashed = "📦"
# untracked = "🤷‍"
style = "green"
staged = '[++\($count\)](green)'
format = '([$all_status$ahead_behind]($style) ) '
disabled = true

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒](bold red)"

[java]
disabled = true

[line_break]
disabled = true

[package]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true
python_binary = "python3"
format = '[${symbol}(${version} )($virtualenv)]($style) '
